In [1]:
import numpy as np

In [89]:
inp = [[6,7,8,9,1,0], [2,4,5,6,7,0]]
inp = [[[i] * 7 for i in each] for each in inp]
inp = np.array(inp, dtype=np.float32)
sequence_shape = inp.shape
batch_size = sequence_shape[0]
seq_length = sequence_shape[1]
width = sequence_shape[2]
inp = np.expand_dims(inp, 1)
inp = np.tile(inp, [1, seq_length, 1, 1])
inp = np.reshape(inp, [-1, seq_length, 7])

In [90]:
positions = np.array([list(range(seq_length)) for _ in range(batch_size)], dtype=np.int32)  # (b, l_t)
positions = np.reshape(positions, -1)
positions = np.expand_dims(positions, 1)
positions
for i in range(batch_size * seq_length):
    inp[i][positions[i]] = [0.5] * 7
positions = np.array([list(range(seq_length)) for _ in range(batch_size)], dtype=np.int32)  # (b, l_t)
positions = np.reshape(positions, -1)

In [91]:
inp.shape

(12, 6, 7)

In [92]:
inp

array([[[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
        [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
        [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[6. , 6. , 6. , 6. , 6. , 6. , 6. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
        [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[6. , 6. , 6. , 6. , 6. , 6. , 6. ],
        [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[6. , 6. , 6. , 6. , 6. , 6. , 6. ],
        [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
        [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    

In [93]:
flat_offsets = seq_length + 1

In [94]:
flat_offsets

7

In [95]:
flat_positions = positions * flat_offsets

In [96]:
flat_positions

array([ 0,  7, 14, 21, 28, 35,  0,  7, 14, 21, 28, 35])

In [97]:
flat_sequence_tensor = np.reshape(inp, [batch_size * seq_length * seq_length, width])
flat_sequence_tensor

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
       [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [6. , 6. , 6. , 6. , 6. , 6. , 6. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
       [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [6. , 6. , 6. , 6. , 6. , 6. , 6. ],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [9. , 9. , 9. , 9. , 9. , 9. , 9. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [6. , 6. , 6. , 6. , 6. , 6. , 6. ],
       [7. , 7. , 7. , 7. , 7. , 7. , 7. ],
       [8. , 8. , 8. , 8. , 8. , 8. , 8. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ,

In [98]:
flat_sequence_tensor.shape

(72, 7)

In [99]:
out = np.take(flat_sequence_tensor, flat_positions, axis=0)
out

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]], dtype=float32)

In [88]:
out.shape

(12, 7)